# Generated by Django 5.1.4 on 2024-12-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Monto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_app.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_app.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_app.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_app.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='investment_app.activo')),
            ],
            options={
                'unique_together': {('activo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=4, max_digits=5)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_app.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_app.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo')},
            },
        ),
    ]
